// Code generated by "stringer -type=Rank"; DO NOT EDIT.

package decks

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Ace-0]
	_ = x[Two-1]
	_ = x[Three-2]
	_ = x[Four-3]
	_ = x[Five-4]
	_ = x[Six-5]
	_ = x[Seven-6]
	_ = x[Eight-7]
	_ = x[Nine-8]
	_ = x[Ten-9]
	_ = x[Jack-10]
	_ = x[Queen-11]
	_ = x[King-12]
	_ = x[RanksCnt-13]
}

const _Rank_name = "AceTwoThreeFourFiveSixSevenEightNineTenJackQueenKingRanksCnt"

var _Rank_index = [...]uint8{0, 3, 6, 11, 15, 19, 22, 27, 32, 36, 39, 43, 48, 52, 60}

func (i Rank) String() string {
	if i >= Rank(len(_Rank_index)-1) {
		return "Rank(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Rank_name[_Rank_index[i]:_Rank_index[i+1]]
}
