// Code generated by "stringer -type=Suit"; DO NOT EDIT.

package decks

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[Clovers-0]
	_ = x[Diamonds-1]
	_ = x[Hearts-2]
	_ = x[Spades-3]
	_ = x[SuitsCnt-4]
}

const _Suit_name = "CloversDiamondsHeartsSpadesSuitsCnt"

var _Suit_index = [...]uint8{0, 7, 15, 21, 27, 35}

func (i Suit) String() string {
	if i >= Suit(len(_Suit_index)-1) {
		return "Suit(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _Suit_name[_Suit_index[i]:_Suit_index[i+1]]
}
